name: Web Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Browser terminal
        uses: fawazahmed0/action-debug@main
        with:
          credentials: "admin:${{ secrets.DEBUG_PASSWORD }}"
